<a href="https://colab.research.google.com/github/arunabh789/Python-and-stats/blob/main/live_project_arunabh_python_stats_edlightened_updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# downloading data of snowman logistics from 05 feb 2023 to 05 feb 2024
import yfinance as yf # load yahoo finance as yf
import pandas as pd

# setting the ticker value
ticker = 'SNOWMAN.ns'
# giving the start and end dates
startDate = '2023-02-05'
endDate = '2024-02-05'

# downloading the data of the ticker value between
# the start and end dates
resultData_snowman = yf.download(ticker, startDate, endDate) # call the function to get data

# printing the last 5 rows of the data
print(resultData_snowman)
resultData_snowman.head()

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close   Volume
Date
2023-02-06  34.549999  35.500000  34.150002  35.000000  33.911079  1100277
2023-02-07  35.200001  35.849998  34.849998  35.400002  34.298637  1445837
2023-02-08  35.299999  37.200001  35.150002  36.750000  35.606636  2060029
2023-02-09  36.599998  37.200001  35.650002  36.049999  34.928413   928673
2023-02-10  35.900002  36.500000  35.650002  35.950001  34.831528   275826
...               ...        ...        ...        ...        ...      ...
2024-01-29  72.849998  73.050003  70.349998  70.650002  69.781105  1715837
2024-01-30  70.000000  71.400002  68.699997  69.250000  68.398323  1466072
2024-01-31  69.900002  74.150002  69.550003  71.900002  71.015732  2735683
2024-02-01  72.449997  73.000000  70.099998  71.400002  70.521881  1232798
2024-02-02  71.949997  73.699997  70.300003  70.800003  69.929260  1847531

[244 rows x 6 columns]

                 Open       High        Low      Close  Adj Close   Volume
Date
2023-02-06  34.549999  35.500000  34.150002  35.000000  33.911079  1100277
2023-02-07  35.200001  35.849998  34.849998  35.400002  34.298637  1445837
2023-02-08  35.299999  37.200001  35.150002  36.750000  35.606636  2060029
2023-02-09  36.599998  37.200001  35.650002  36.049999  34.928413   928673
2023-02-10  35.900002  36.500000  35.650002  35.950001  34.831528   275826

In [ ]:
resultData_snowman["Snowman_Return"] = resultData_snowman["Adj Close"].pct_change() # percentage change
resultData_snowman["Snowman_Return"] # (Today Price - Yesterday Price) /Yesterday Price
resultData_snowman["Snowman_Return"][1:]

Date
2023-02-07    0.011429
2023-02-08    0.038136
2023-02-09   -0.019048
2023-02-10   -0.002774
2023-02-13   -0.026426
                ...
2024-01-29   -0.020790
2024-01-30   -0.019816
2024-01-31    0.038267
2024-02-01   -0.006954
2024-02-02   -0.008403
Name: Snowman_Return, Length: 243, dtype: float64

In [ ]:
import pandas as pd
snowman_return_df = pd.DataFrame(resultData_snowman["Snowman_Return"][1:])

In [ ]:
import numpy as np
from scipy.stats import shapiro
from scipy.stats import levene
import scipy.stats as stats

In [ ]:
import pandas as pd
snowman_return_df = pd.DataFrame(resultData_snowman["Snowman_Return"][1:])
alpha = 0.05

In [ ]:
shapiro(snowman_return_df)
# conduct the  Shapiro-Wilk Test
#p_value > alpha:
    #print("We do not reject the null hypothesis that data is normal")
#else:
    #print("Reject the Null Hypothesis hat data is normal")

ShapiroResult(statistic=0.9024561894726447, pvalue=1.8316355127116264e-11)

In [ ]:
# downloading data of paytm from 05 aug 2023 to 05 feb 2024
import yfinance as yf # load yahoo finance as yf
import pandas as pd

# setting the ticker value
ticker = 'PAYTM.NS'
# giving the start and end dates
startDate = '2023-08-05'
endDate = '2024-02-05'

# downloading the data of the ticker value between
# the start and end dates
resultData_paytm = yf.download(ticker, startDate, endDate) # call the function to get data

# printing the last 5 rows of the data
print(resultData_paytm)
resultData_paytm.head()

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2023-08-07  865.000000  887.700012  835.250000  850.700012  850.700012
2023-08-08  840.950012  849.700012  827.299988  830.650024  830.650024
2023-08-09  828.799988  845.900024  825.049988  838.549988  838.549988
2023-08-10  836.950012  867.799988  833.650024  858.099976  858.099976
2023-08-11  858.099976  873.000000  853.000000  864.549988  864.549988
...                ...         ...         ...         ...         ...
2024-01-29  763.950012  768.900024  747.049988  752.049988  752.049988
2024-01-30  753.000000  767.000000  753.000000  761.099976  761.099976
2024-01-31  758.150024  774.299988  753.099976  761.200012  761.200012
2024-02-01  609.000000  609.000000  609.000000  609.000000  609.000000
2024-02-02  487.200012  487.200012  487.200012  487.200012  487.200012

              Volume
Date
2023-08-07  12517134
2023-08-08   2336306
2023-08-09   1980457
2023-08-10   4366573
2023-08-11   3686481
...              ...
2024-01-29   3108252
2024-01-30   3415910
2024-01-31   2932281
2024-02-01   1319654
2024-02-02   8816560

[121 rows x 6 columns]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-08-07,865.000000,887.700012,835.250000,850.700012,850.700012,12517134
2023-08-08,840.950012,849.700012,827.299988,830.650024,830.650024,2336306
2023-08-09,828.799988,845.900024,825.049988,838.549988,838.549988,1980457
2023-08-10,836.950012,867.799988,833.650024,858.099976,858.099976,4366573
2023-08-11,858.099976,873.000000,853.000000,864.549988,864.549988,3686481

In [ ]:
resultData_paytm["Paytm_Return"] = resultData_paytm["Adj Close"].pct_change() # percentage change
resultData_paytm["Paytm_Return"] # (Today Price - Yesterday Price) /Yesterday Price
resultData_paytm["Paytm_Return"][1:]

Date
2023-08-08   -0.023569
2023-08-09    0.009511
2023-08-10    0.023314
2023-08-11    0.007517
2023-08-14   -0.000868
                ...
2024-01-29   -0.014416
2024-01-30    0.012034
2024-01-31    0.000131
2024-02-01   -0.199947
2024-02-02   -0.200000
Name: Paytm_Return, Length: 120, dtype: float64

In [ ]:
import pandas as pd
Paytm_Return_df = pd.DataFrame(resultData_paytm["Paytm_Return"][1:])

In [ ]:
import numpy as np
from scipy.stats import shapiro
from scipy.stats import levene
import scipy.stats as stats

In [ ]:
import pandas as pd
Paytm_Return_df = pd.DataFrame(resultData_paytm["Paytm_Return"][1:])
alpha = 0.05

In [ ]:
shapiro(Paytm_Return_df)
# conduct the  Shapiro-Wilk Test
#if p_value > alpha:
#    print("We do not reject the null hypothesis that data is normal")
#else:
#    print("Reject the Null Hypothesis hat data is norma")

ShapiroResult(statistic=0.692910953964425, pvalue=1.6466014043859363e-14)

In [ ]:
# downloading data of zomato from 05 nov 2023 to 05 feb 2024
import yfinance as yf # load yahoo finance as yf
import pandas as pd

# setting the ticker value
ticker = 'ZOMATO.NS'
# giving the start and end dates
startDate = '2023-11-05'
endDate = '2024-02-05'

# downloading the data of the ticker value between
# the start and end dates
resultData_zomato = yf.download(ticker, startDate, endDate) # call the function to get data

# printing the last 5 rows of the data
print(resultData_zomato)
resultData_zomato.head()

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2023-11-06  119.599998  123.900002  118.250000  123.300003  123.300003
2023-11-07  123.550003  126.349998  120.500000  121.300003  121.300003
2023-11-08  122.000000  125.699997  121.300003  125.150002  125.150002
2023-11-09  125.250000  125.550003  121.349998  121.849998  121.849998
2023-11-10  122.000000  123.300003  120.699997  121.300003  121.300003
2023-11-13  122.650002  123.099998  121.500000  122.199997  122.199997
2023-11-15  123.300003  125.199997  119.750000  120.250000  120.250000
2023-11-16  120.900002  122.550003  120.699997  121.849998  121.849998
2023-11-17  122.000000  125.000000  121.500000  122.199997  122.199997
2023-11-20  122.849998  123.400002  117.349998  118.150002  118.150002
2023-11-21  118.550003  119.000000  116.050003  116.500000  116.500000
2023-11-22  116.000000  117.800003  114.349998  115.300003  115.300003
2023-11-23  113.599998  115.750000  112.500000  112.949997  112.949997
2023-11-24  114.150002  116.000000  112.900002  113.250000  113.250000
2023-11-28  114.900002  116.900002  113.500000  113.800003  113.800003
2023-11-29  117.000000  119.199997  114.000000  116.599998  116.599998
2023-11-30  118.800003  120.699997  116.150002  118.550003  118.550003
2023-12-01  118.000000  118.349998  115.099998  116.300003  116.300003
2023-12-04  118.750000  119.000000  116.250000  117.400002  117.400002
2023-12-05  117.900002  118.250000  116.250000  116.750000  116.750000
2023-12-06  117.150002  119.699997  116.599998  118.900002  118.900002
2023-12-07  119.599998  122.199997  118.400002  121.699997  121.699997
2023-12-08  123.000000  123.900002  119.300003  119.949997  119.949997
2023-12-11  119.949997  120.500000  117.550003  118.449997  118.449997
2023-12-12  119.000000  119.300003  114.150002  116.750000  116.750000
2023-12-13  116.900002  120.500000  116.150002  120.000000  120.000000
2023-12-14  121.000000  124.949997  120.500000  124.150002  124.150002
2023-12-15  124.500000  125.000000  122.400002  123.599998  123.599998
2023-12-18  123.400002  129.199997  121.550003  128.550003  128.550003
2023-12-19  129.000000  131.750000  127.400002  130.250000  130.250000
2023-12-20  130.350006  131.000000  123.150002  124.750000  124.750000
2023-12-21  122.150002  128.699997  120.199997  127.349998  127.349998
2023-12-22  130.550003  131.000000  125.300003  128.500000  128.500000
2023-12-26  128.500000  128.699997  124.300003  125.000000  125.000000
2023-12-27  125.699997  127.599998  125.550003  127.050003  127.050003
2023-12-28  124.900002  125.500000  120.599998  123.199997  123.199997
2023-12-29  124.000000  125.550003  123.250000  123.699997  123.699997
2024-01-01  124.449997  125.599998  122.849998  124.500000  124.500000
2024-01-02  127.000000  129.449997  125.500000  128.699997  128.699997
2024-01-03  128.800003  130.250000  127.099998  127.550003  127.550003
2024-01-04  128.399994  130.899994  126.449997  129.750000  129.750000
2024-01-05  130.899994  134.350006  128.949997  133.300003  133.300003
2024-01-08  133.649994  133.649994  130.000000  132.850006  132.850006
2024-01-09  133.199997  135.000000  132.600006  134.300003  134.300003
2024-01-10  134.250000  136.149994  132.250000  134.649994  134.649994
2024-01-11  135.300003  139.000000  135.050003  138.350006  138.350006
2024-01-12  140.000000  141.500000  136.800003  139.550003  139.550003
2024-01-15  139.550003  139.550003  139.550003  139.550003  139.550003
2024-01-16  135.000000  135.300003  131.000000  133.550003  133.550003
2024-01-17  132.399994  132.399994  126.750000  127.400002  127.400002
2024-01-18  128.050003  129.800003  121.599998  129.449997  129.449997
2024-01-19  130.500000  135.500000  128.000000  135.050003  135.050003
2024-01-23  136.300003  137.300003  127.000000  130.100006  130.100006
2024-01-24  131.449997  136.899994  129.800003  136.199997  136.199997
2024-01-25  135.899994  138.199997  132.800003  136.149994  136.149994
2024-01-29  136.899994  137.699997  132.350006  135.550003  135.550003
2024-01-30  135.850006  138.800003  134.649994  137.199997  137.199997
2024-01-31  140.000000  142.000000  138.000000  139.550003  139.550003
2024-02-01  141.000000  143.500000  138.550003  140.550003  140.550003
2024-02-02  141.800003  145.000000  141.449997  143.800003  143.800003

               Volume
Date
2023-11-06  186288904
2023-11-07  120886007
2023-11-08   75041688
2023-11-09   50307832
2023-11-10   43388163
2023-11-13   28348143
2023-11-15   60088818
2023-11-16   36895083
2023-11-17   43882213
2023-11-20   52784478
2023-11-21   45193553
2023-11-22   52799865
2023-11-23   56329090
2023-11-24   49980086
2023-11-28   61963724
2023-11-29  115274058
2023-11-30  225208168
2023-12-01   57261076
2023-12-04   66057180
2023-12-05   57483305
2023-12-06   48171753
2023-12-07   52483562
2023-12-08   44213196
2023-12-11   32372287
2023-12-12   40800538
2023-12-13   48092329
2023-12-14   74178495
2023-12-15   39542770
2023-12-18   89553155
2023-12-19   64117314
2023-12-20   49006056
2023-12-21   52326124
2023-12-22   63113800
2023-12-26   25499782
2023-12-27   21757560
2023-12-28   72865479
2023-12-29   27512604
2024-01-01   24228685
2024-01-02   69395959
2024-01-03   39101172
2024-01-04   45285624
2024-01-05   55608923
2024-01-08   38912423
2024-01-09   33803263
2024-01-10   29917881
2024-01-11   41809415
2024-01-12   45508277
2024-01-15          0
2024-01-16   47043428
2024-01-17   76780526
2024-01-18  111946831
2024-01-19   81155018
2024-01-23   72520625
2024-01-24   54612769
2024-01-25   60682540
2024-01-29   55871017
2024-01-30   57612020
2024-01-31   89833027
2024-02-01   70252449
2024-02-02   78666454

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-11-06,119.599998,123.900002,118.250000,123.300003,123.300003,186288904
2023-11-07,123.550003,126.349998,120.500000,121.300003,121.300003,120886007
2023-11-08,122.000000,125.699997,121.300003,125.150002,125.150002,75041688
2023-11-09,125.250000,125.550003,121.349998,121.849998,121.849998,50307832
2023-11-10,122.000000,123.300003,120.699997,121.300003,121.300003,43388163

In [ ]:
resultData_zomato["Zomato_Return"] = resultData_zomato["Adj Close"].pct_change() # percentage change
resultData_zomato["Zomato_Return"] # (Today Price - Yesterday Price) /Yesterday Price
resultData_zomato["Zomato_Return"][1:]

Date
2023-11-07   -0.016221
2023-11-08    0.031739
2023-11-09   -0.026368
2023-11-10   -0.004514
2023-11-13    0.007420
2023-11-15   -0.015957
2023-11-16    0.013306
2023-11-17    0.002872
2023-11-20   -0.033142
2023-11-21   -0.013965
2023-11-22   -0.010300
2023-11-23   -0.020382
2023-11-24    0.002656
2023-11-28    0.004857
2023-11-29    0.024605
2023-11-30    0.016724
2023-12-01   -0.018979
2023-12-04    0.009458
2023-12-05   -0.005537
2023-12-06    0.018415
2023-12-07    0.023549
2023-12-08   -0.014380
2023-12-11   -0.012505
2023-12-12   -0.014352
2023-12-13    0.027837
2023-12-14    0.034583
2023-12-15   -0.004430
2023-12-18    0.040049
2023-12-19    0.013224
2023-12-20   -0.042226
2023-12-21    0.020842
2023-12-22    0.009030
2023-12-26   -0.027237
2023-12-27    0.016400
2023-12-28   -0.030303
2023-12-29    0.004058
2024-01-01    0.006467
2024-01-02    0.033735
2024-01-03   -0.008935
2024-01-04    0.017248
2024-01-05    0.027360
2024-01-08   -0.003376
2024-01-09    0.010915
2024-01-10    0.002606
2024-01-11    0.027479
2024-01-12    0.008674
2024-01-15    0.000000
2024-01-16   -0.042995
2024-01-17   -0.046050
2024-01-18    0.016091
2024-01-19    0.043260
2024-01-23   -0.036653
2024-01-24    0.046887
2024-01-25   -0.000367
2024-01-29   -0.004407
2024-01-30    0.012173
2024-01-31    0.017128
2024-02-01    0.007166
2024-02-02    0.023123
Name: Zomato_Return, dtype: float64

In [ ]:
import pandas as pd
Zomato_Return_df = pd.DataFrame(resultData_zomato["Zomato_Return"][1:])

In [ ]:
import numpy as np
from scipy.stats import shapiro
from scipy.stats import levene
import scipy.stats as stats

In [ ]:
import pandas as pd
Zomato_Return_df = pd.DataFrame(resultData_zomato["Zomato_Return"][1:])
alpha = 0.05

In [ ]:
shapiro(Zomato_Return_df)

ShapiroResult(statistic=0.9835003257304317, pvalue=0.6038508017256858)

In [ ]:
import pandas as pd
snowman_return_df = pd.DataFrame(resultData_snowman["Snowman_Return"][1:])
Paytm_Return_df = pd.DataFrame(resultData_paytm["Paytm_Return"][1:])
Zomato_Return_df = pd.DataFrame(resultData_zomato["Zomato_Return"][1:])

combined_df = pd.concat([snowman_return_df, Paytm_Return_df, Zomato_Return_df], axis=1)
combined_df.columns = ["Snowman_Return", "Paytm_Return", "Zomato_Return"]

print(combined_df.head())
combined_df.head()

            Snowman_Return  Paytm_Return  Zomato_Return
Date
2023-02-07        0.011429           NaN            NaN
2023-02-08        0.038136           NaN            NaN
2023-02-09       -0.019048           NaN            NaN
2023-02-10       -0.002774           NaN            NaN
2023-02-13       -0.026426           NaN            NaN

            Snowman_Return  Paytm_Return  Zomato_Return
Date
2023-02-07        0.011429           NaN            NaN
2023-02-08        0.038136           NaN            NaN
2023-02-09       -0.019048           NaN            NaN
2023-02-10       -0.002774           NaN            NaN
2023-02-13       -0.026426           NaN            NaN

In [ ]:
combined_df = combined_df.dropna()
combined_df.head()

            Snowman_Return  Paytm_Return  Zomato_Return
Date
2023-11-07       -0.028999      0.001136      -0.016221
2023-11-08       -0.017341      0.016446       0.031739
2023-11-09       -0.027451     -0.001785      -0.026368
2023-11-10        0.003024     -0.000447      -0.004514
2023-11-13        0.022111      0.000559       0.007420

In [ ]:

import pandas as pd
from scipy.stats import levene
df = pd.DataFrame(combined_df)
stat, pval = levene(df['Snowman_Return'], df['Paytm_Return'], df['Zomato_Return'])
print(f'Levene statistic: {stat:.4f}, p-value: {pval:.4f}')

Levene statistic: 0.7073, p-value: 0.4944

In [ ]:

import pandas as pd
from scipy import stats

# Load the data from the combined_df dataframe
df = pd.DataFrame(combined_df)

# Extract the three return columns
snowman_return = df['Snowman_Return']
paytm_return = df['Paytm_Return']
zomato_return = df['Zomato_Return']

# Perform one-way ANOVA
f_statistic, p_value = stats.f_oneway(snowman_return, paytm_return, zomato_return)

# Print the results
print(f'F-statistic: {f_statistic:.4f}, p-value: {p_value:.4f}')

# Interpret the results
if p_value < 0.05:
    print('There is a statistically significant difference between the mean returns of the three stocks.')
else:
    print('There is no statistically significant difference between the mean returns of the three stocks.')

F-statistic: 2.5458, p-value: 0.0813
There is no statistically significant difference between the mean returns of the three stocks.

In [ ]:
import pandas as pd
import scipy.stats as stats

# Load the data from the combined_df dataframe
df = pd.DataFrame(combined_df)

# Extract the three return columns
snowman_return = df['Snowman_Return']
paytm_return = df['Paytm_Return']
zomato_return = df['Zomato_Return']

# Perform two-sample t-tests between each pair of stocks
t_statistic, p_value = stats.ttest_ind(snowman_return, paytm_return)
print(f'snowman and zomato T-statistic: {t_statistic:.4f}, p-value: {p_value:.4f}')

t_statistic, p_value = stats.ttest_ind(snowman_return, zomato_return)
print(f'T-statistic: {t_statistic:.4f}, p-value: {p_value:.4f}')

t_statistic, p_value = stats.ttest_ind(paytm_return, zomato_return)
print(f'T-statistic: {t_statistic:.4f}, p-value: {p_value:.4f}')

t_statistic, p_value = stats.ttest_ind(paytm_return, snowman_return)
print(f'T-statistic: {t_statistic:.4f}, p-value: {p_value:.4f}')

t_statistic, p_value = stats.ttest_ind(zomato_return, snowman_return)
print(f'T-statistic: {t_statistic:.4f}, p-value: {p_value:.4f}')

t_statistic, p_value = stats.ttest_ind(zomato_return, paytm_return)
print(f'T-statistic: {t_statistic:.4f}, p-value: {p_value:.4f}')

 snowman and zomato T-statistic: 1.8455, p-value: 0.0675
T-statistic: 0.4716, p-value: 0.6381
T-statistic: -1.6762, p-value: 0.0964
T-statistic: -1.8455, p-value: 0.0675
T-statistic: -0.4716, p-value: 0.6381
T-statistic: 1.6762, p-value: 0.0964

In [ ]:
####Q3# Finding beta of all the 3 companies
# downloading data of snowman logistics from 05 feb 2023 to 05 feb 2024
import yfinance as yf # load yahoo finance as yf
import pandas as pd

# setting the ticker value
ticker = 'SNOWMAN.ns'
# giving the start and end dates
startDate = '2023-02-05'
endDate = '2024-02-05'

# downloading the data of the ticker value between
# the start and end dates
resultData_snowman = yf.download(ticker, startDate, endDate) # call the function to get data

# printing the last 5 rows of the data
print(resultData_snowman)
resultData_snowman.head()

[*********************100%***********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close   Volume
Date
2023-02-06  34.549999  35.500000  34.150002  35.000000  33.911079  1100277
2023-02-07  35.200001  35.849998  34.849998  35.400002  34.298637  1445837
2023-02-08  35.299999  37.200001  35.150002  36.750000  35.606636  2060029
2023-02-09  36.599998  37.200001  35.650002  36.049999  34.928413   928673
2023-02-10  35.900002  36.500000  35.650002  35.950001  34.831528   275826
...               ...        ...        ...        ...        ...      ...
2024-01-29  72.849998  73.050003  70.349998  70.650002  69.781105  1715837
2024-01-30  70.000000  71.400002  68.699997  69.250000  68.398323  1466072
2024-01-31  69.900002  74.150002  69.550003  71.900002  71.015732  2735683
2024-02-01  72.449997  73.000000  70.099998  71.400002  70.521881  1232798
2024-02-02  71.949997  73.699997  70.300003  70.800003  69.929260  1847531

[244 rows x 6 columns]

                 Open       High        Low      Close  Adj Close   Volume
Date
2023-02-06  34.549999  35.500000  34.150002  35.000000  33.911079  1100277
2023-02-07  35.200001  35.849998  34.849998  35.400002  34.298637  1445837
2023-02-08  35.299999  37.200001  35.150002  36.750000  35.606636  2060029
2023-02-09  36.599998  37.200001  35.650002  36.049999  34.928413   928673
2023-02-10  35.900002  36.500000  35.650002  35.950001  34.831528   275826

In [ ]:
resultData_snowman["Snowman_Return"] = resultData_snowman["Adj Close"].pct_change() # percentage change
resultData_snowman["Snowman_Return"] # (Today Price - Yesterday Price) /Yesterday Price
resultData_snowman["Snowman_Return"][1:]

Date
2023-02-07    0.011429
2023-02-08    0.038136
2023-02-09   -0.019048
2023-02-10   -0.002774
2023-02-13   -0.026426
                ...
2024-01-29   -0.020790
2024-01-30   -0.019816
2024-01-31    0.038267
2024-02-01   -0.006954
2024-02-02   -0.008403
Name: Snowman_Return, Length: 243, dtype: float64

In [ ]:
ticker = "^NSEI"
df_nifty = yf.download(ticker, start="2023-02-05", end="2024-02-05")
df_nifty.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-02-06,17818.550781,17823.699219,17698.349609,17764.599609,17764.599609,282500
2023-02-07,17790.099609,17811.150391,17652.550781,17721.500000,17721.500000,354400
2023-02-08,17750.300781,17898.699219,17744.150391,17871.699219,17871.699219,291000
2023-02-09,17885.500000,17916.900391,17779.800781,17893.449219,17893.449219,260900
2023-02-10,17847.550781,17876.949219,17801.000000,17856.500000,17856.500000,232000

In [ ]:
df_nifty["NIFTY_50"] = df_nifty["Adj Close"].pct_change()
df_nifty["NIFTY_50"][1:]

Date
2023-02-07   -0.002426
2023-02-08    0.008476
2023-02-09    0.001217
2023-02-10   -0.002065
2023-02-13   -0.004794
                ...
2024-01-29    0.018031
2024-01-30   -0.009914
2024-01-31    0.009460
2024-02-01   -0.001300
2024-02-02    0.007206
Name: NIFTY_50, Length: 243, dtype: float64

In [ ]:
# Beta of a Stock
y = df_nifty["NIFTY_50"][1:]
x = resultData_snowman["Snowman_Return"][1:]
# Beta = measure of risk;  higher the risk; higher the return
# Beta formula from stats Beta = Covar(Returns of Reliance, Returns of NIFTY)/ Variance of Nifty
# Python does not have a direct formula for computing Beta
# Indirect: Correlation = Cov(Reliance_Ret, NIFTY_Ret)/ Std.dev(Reliance). Std.dev(NIFTY)
correlation = x.corr(y)
# Standard Deviation of Reliance and Standard Deviation of NIFTY
xstd = x.std()
ystd = y.std()
# Correltion * Std. Dev Nifty / Std.Dev RIL = Covar(Reliance, NIFTY)/ (std.NIFTY, std.Rel)
Beta = correlation * xstd/ystd
Beta

0.8376978741878844

In [ ]:
# downloading data of paytm from 05 aug 2023 to 05 feb 2024
import yfinance as yf # load yahoo finance as yf
import pandas as pd

# setting the ticker value
ticker = 'PAYTM.NS'
# giving the start and end dates
startDate = '2023-08-05'
endDate = '2024-02-05'

# downloading the data of the ticker value between
# the start and end dates
resultData_paytm = yf.download(ticker, startDate, endDate) # call the function to get data

# printing the last 5 rows of the data
print(resultData_paytm)
resultData_paytm.head()

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2023-08-07  865.000000  887.700012  835.250000  850.700012  850.700012
2023-08-08  840.950012  849.700012  827.299988  830.650024  830.650024
2023-08-09  828.799988  845.900024  825.049988  838.549988  838.549988
2023-08-10  836.950012  867.799988  833.650024  858.099976  858.099976
2023-08-11  858.099976  873.000000  853.000000  864.549988  864.549988
...                ...         ...         ...         ...         ...
2024-01-29  763.950012  768.900024  747.049988  752.049988  752.049988
2024-01-30  753.000000  767.000000  753.000000  761.099976  761.099976
2024-01-31  758.150024  774.299988  753.099976  761.200012  761.200012
2024-02-01  609.000000  609.000000  609.000000  609.000000  609.000000
2024-02-02  487.200012  487.200012  487.200012  487.200012  487.200012

              Volume
Date
2023-08-07  12517134
2023-08-08   2336306
2023-08-09   1980457
2023-08-10   4366573
2023-08-11   3686481
...              ...
2024-01-29   3108252
2024-01-30   3415910
2024-01-31   2932281
2024-02-01   1319654
2024-02-02   8816560

[121 rows x 6 columns]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-08-07,865.000000,887.700012,835.250000,850.700012,850.700012,12517134
2023-08-08,840.950012,849.700012,827.299988,830.650024,830.650024,2336306
2023-08-09,828.799988,845.900024,825.049988,838.549988,838.549988,1980457
2023-08-10,836.950012,867.799988,833.650024,858.099976,858.099976,4366573
2023-08-11,858.099976,873.000000,853.000000,864.549988,864.549988,3686481

In [ ]:
resultData_paytm["Paytm_Return"] = resultData_paytm["Adj Close"].pct_change() # percentage change
resultData_paytm["Paytm_Return"] # (Today Price - Yesterday Price) /Yesterday Price
resultData_paytm["Paytm_Return"][1:]

Date
2023-08-08   -0.023569
2023-08-09    0.009511
2023-08-10    0.023314
2023-08-11    0.007517
2023-08-14   -0.000868
                ...
2024-01-29   -0.014416
2024-01-30    0.012034
2024-01-31    0.000131
2024-02-01   -0.199947
2024-02-02   -0.200000
Name: Paytm_Return, Length: 120, dtype: float64

In [ ]:
ticker = "^NSEI"
df_nifty = yf.download(ticker, start="2023-08-05", end="2024-02-05")
df_nifty.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-08-07,19576.849609,19620.449219,19524.800781,19597.300781,19597.300781,216600
2023-08-08,19627.199219,19634.400391,19533.099609,19570.849609,19570.849609,260300
2023-08-09,19578.800781,19645.500000,19467.500000,19632.550781,19632.550781,266500
2023-08-10,19605.550781,19623.599609,19495.400391,19543.099609,19543.099609,312200
2023-08-11,19554.250000,19557.750000,19412.750000,19428.300781,19428.300781,235500

In [ ]:
df_nifty["NIFTY_50"] = df_nifty["Adj Close"].pct_change()
df_nifty["NIFTY_50"][1:]

Date
2023-08-08   -0.001350
2023-08-09    0.003153
2023-08-10   -0.004556
2023-08-11   -0.005874
2023-08-14    0.000322
                ...
2024-01-29    0.018031
2024-01-30   -0.009914
2024-01-31    0.009460
2024-02-01   -0.001300
2024-02-02    0.007206
Name: NIFTY_50, Length: 120, dtype: float64

In [ ]:
# Beta of a Stock
y = df_nifty["NIFTY_50"][1:]
x = resultData_paytm["Paytm_Return"][1:]
# Beta = measure of risk;  higher the risk; higher the return
# Beta formula from stats Beta = Covar(Returns of Reliance, Returns of NIFTY)/ Variance of Nifty
# Python does not have a direct formula for computing Beta
# Indirect: Correlation = Cov(Reliance_Ret, NIFTY_Ret)/ Std.dev(Reliance). Std.dev(NIFTY)
correlation = x.corr(y)
# Standard Deviation of Reliance and Standard Deviation of NIFTY
xstd = x.std()
ystd = y.std()
# Correltion * Std. Dev Nifty / Std.Dev RIL = Covar(Reliance, NIFTY)/ (std.NIFTY, std.Rel)
Beta = correlation * xstd/ystd
Beta

0.5287788702221398

In [ ]:
# downloading data of zomato from 05 nov 2023 to 05 feb 2024
import yfinance as yf # load yahoo finance as yf
import pandas as pd

# setting the ticker value
ticker = 'ZOMATO.NS'
# giving the start and end dates
startDate = '2023-11-05'
endDate = '2024-02-05'

# downloading the data of the ticker value between
# the start and end dates
resultData_zomato = yf.download(ticker, startDate, endDate) # call the function to get data

# printing the last 5 rows of the data
resultData_zomato.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-11-06,119.599998,123.900002,118.250000,123.300003,123.300003,186288904
2023-11-07,123.550003,126.349998,120.500000,121.300003,121.300003,120886007
2023-11-08,122.000000,125.699997,121.300003,125.150002,125.150002,75041688
2023-11-09,125.250000,125.550003,121.349998,121.849998,121.849998,50307832
2023-11-10,122.000000,123.300003,120.699997,121.300003,121.300003,43388163

In [ ]:
resultData_zomato["Zomato_Return"] = resultData_zomato["Adj Close"].pct_change() # percentage change
resultData_zomato["Zomato_Return"] # (Today Price - Yesterday Price) /Yesterday Price
resultData_zomato["Zomato_Return"][1:]

Date
2023-11-07   -0.016221
2023-11-08    0.031739
2023-11-09   -0.026368
2023-11-10   -0.004514
2023-11-13    0.007420
2023-11-15   -0.015957
2023-11-16    0.013306
2023-11-17    0.002872
2023-11-20   -0.033142
2023-11-21   -0.013965
2023-11-22   -0.010300
2023-11-23   -0.020382
2023-11-24    0.002656
2023-11-28    0.004857
2023-11-29    0.024605
2023-11-30    0.016724
2023-12-01   -0.018979
2023-12-04    0.009458
2023-12-05   -0.005537
2023-12-06    0.018415
2023-12-07    0.023549
2023-12-08   -0.014380
2023-12-11   -0.012505
2023-12-12   -0.014352
2023-12-13    0.027837
2023-12-14    0.034583
2023-12-15   -0.004430
2023-12-18    0.040049
2023-12-19    0.013224
2023-12-20   -0.042226
2023-12-21    0.020842
2023-12-22    0.009030
2023-12-26   -0.027237
2023-12-27    0.016400
2023-12-28   -0.030303
2023-12-29    0.004058
2024-01-01    0.006467
2024-01-02    0.033735
2024-01-03   -0.008935
2024-01-04    0.017248
2024-01-05    0.027360
2024-01-08   -0.003376
2024-01-09    0.010915
2024-01-10    0.002606
2024-01-11    0.027479
2024-01-12    0.008674
2024-01-15    0.000000
2024-01-16   -0.042995
2024-01-17   -0.046050
2024-01-18    0.016091
2024-01-19    0.043260
2024-01-23   -0.036653
2024-01-24    0.046887
2024-01-25   -0.000367
2024-01-29   -0.004407
2024-01-30    0.012173
2024-01-31    0.017128
2024-02-01    0.007166
2024-02-02    0.023123
Name: Zomato_Return, dtype: float64

In [ ]:
ticker = "^NSEI"
df_nifty = yf.download(ticker, start="2023-11-05", end="2024-02-05")
df_nifty.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-11-06,19345.849609,19423.000000,19309.699219,19411.750000,19411.750000,180700
2023-11-07,19404.050781,19423.500000,19329.099609,19406.699219,19406.699219,198700
2023-11-08,19449.599609,19464.400391,19401.500000,19443.500000,19443.500000,195000
2023-11-09,19457.400391,19463.900391,19378.349609,19395.300781,19395.300781,208400
2023-11-10,19351.849609,19451.300781,19329.449219,19425.349609,19425.349609,152200

In [ ]:
df_nifty["NIFTY_50"] = df_nifty["Adj Close"].pct_change()
df_nifty["NIFTY_50"][1:]

Date
2023-11-07   -0.000260
2023-11-08    0.001896
2023-11-09   -0.002479
2023-11-10    0.001549
2023-11-13    0.000937
2023-11-15    0.011927
2023-11-16    0.004562
2023-11-17   -0.001690
2023-11-20   -0.001916
2023-11-21    0.004539
2023-11-22    0.001438
2023-11-23   -0.000497
2023-11-24   -0.000369
2023-11-28    0.004799
2023-11-29    0.010402
2023-11-30    0.001819
2023-12-01    0.006693
2023-12-04    0.020668
2023-12-05    0.008136
2023-12-06    0.003961
2023-12-07   -0.001746
2023-12-08    0.003265
2023-12-11    0.001321
2023-12-12   -0.004320
2023-12-13    0.000954
2023-12-14    0.012250
2023-12-15    0.012933
2023-12-18   -0.001771
2023-12-19    0.001608
2023-12-20   -0.014121
2023-12-21    0.004960
2023-12-22    0.004439
2023-12-26    0.004307
2023-12-27    0.009953
2023-12-28    0.005724
2023-12-29   -0.002172
2024-01-01    0.000483
2024-01-02   -0.003500
2024-01-03   -0.006852
2024-01-04    0.006564
2024-01-05    0.002410
2024-01-08   -0.009111
2024-01-09    0.001480
2024-01-10    0.003428
2024-01-11    0.001318
2024-01-12    0.011426
2024-01-15    0.009267
2024-01-16   -0.002948
2024-01-17   -0.020894
2024-01-18   -0.005085
2024-01-19    0.007462
2024-01-23   -0.017741
2024-01-24    0.010130
2024-01-25   -0.004724
2024-01-29    0.018031
2024-01-30   -0.009914
2024-01-31    0.009460
2024-02-01   -0.001300
2024-02-02    0.007206
Name: NIFTY_50, dtype: float64

In [ ]:
# Beta of a Stock
y = df_nifty["NIFTY_50"][1:]
x = resultData_zomato["Zomato_Return"][1:]
# Beta = measure of risk;  higher the risk; higher the return
# Beta formula from stats Beta = Covar(Returns of Reliance, Returns of NIFTY)/ Variance of Nifty
# Python does not have a direct formula for computing Beta
# Indirect: Correlation = Cov(Reliance_Ret, NIFTY_Ret)/ Std.dev(Reliance). Std.dev(NIFTY)
correlation = x.corr(y)
# Standard Deviation of Reliance and Standard Deviation of NIFTY
xstd = x.std()
ystd = y.std()
# Correltion * Std. Dev Nifty / Std.Dev RIL = Covar(Reliance, NIFTY)/ (std.NIFTY, std.Rel)
Beta = correlation * xstd/ystd
Beta

1.1448777675962527